language: r
cache: packages
latex: false
fortran: false

matrix:
  include:
    - dist: precise
      r: 3.5.3
    - dist: trusty
    - dist: xenial
      env: R_CODECOV=true
      r_packages: covr
    - dist: bionic
    - os: osx
      osx_image: xcode10.2
    - os: osx
      osx_image: xcode9.4
    - os: osx
      brew_packages: curl
      env: PKG_CONFIG_PATH="/usr/local/opt/curl/lib/pkgconfig"
    - os: osx
      brew_packages: curl-openssl
      env:
        - PKG_CONFIG_PATH="/usr/local/opt/curl-openssl/lib/pkgconfig"
        - HTTPBIN_TEST_SERVER="https://nghttp2.org/httpbin"
    - os: osx
      before_install: brew install curl --HEAD
      env: PKG_CONFIG_PATH="/usr/local/opt/curl/lib/pkgconfig"
    - os: osx
      osx_image: xcode7.3
      disable_homebrew: true
      before_install: sed -i.bak 's/-isysroot /-I/g' $(R RHOME)/etc/Makeconf

addons:
  apt:
    packages:
    - libcurl4-openssl-dev

after_success:
  - if [[ "${R_CODECOV}" ]]; then R -e 'covr::codecov()'; fi
